### ISSUE TITLE
add support for ecdsa-sha2-nistp256

### ISSUE THREAD

**Issue by karcaw** [EasyPost/ssh_certificate_parser#11]
can you add support for the ecdsa-sha2-nistp256 type as well, simalar to what was done in #8 

I can confirm that adding it manually works

**Comment by Justintime50** [comment]
Hey @karcaw we'd love to have you submit a PR! Once done and testing details provided, we'll take a look and see about a release.

**Comment by Justintime50** [comment]
This has been released via v1.5.0
